name: production

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ contains(github.ref, 'refs/heads/release/') }} or ${{ contains(github.ref, 'refs/tag/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        env
        ls -la
  tag:
    needs: deploy
    if: ${{ contains(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch ntcase binary file
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo:  kurosawa-tc/ntgtag
        version: latest
        file: ntgtag_linux_x86_64.tar.gz
        #token: ${{ secrets.NTCASE_TOKEN }}
    - name: Install ntgtag command
      run: |
        sudo tar xzf ntgtag_linux_x86_64.tar.gz -C /usr/local/bin
        sudo chmod +x /usr/local/bin/ntgtag
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15
    - run: |
        _CUSTOM_TAG=$(git tag -l | ntgtag $GITHUB_REF)
        git tag -l
        git tag $_CUSTOM_TAG
        git tag -l
        git push -u origin $_CUSTOM_TAG
