name: production

on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'deployと入力してください'
        required: true
        default: ''

jobs:
  deploy:
    if: github.event.inputs.logLevel == 'deploy' && ${{ startsWith(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        env
        ls -la
