name: production

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ contains(github.ref, 'refs/heads/release/') }} or ${{ contains(github.ref, 'refs/tag/') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        env
        ls -la
