name: slack-notification
on:
  workflow_run:
    workflows:
    - private_exclusive
    - private_common
    - alpha
    - production
    types:
    - requested
    - completed

jobs:
  on-requested:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.21.0
      if: ${{ github.event.workflow_run.conclusion == '' }}
      with:
        channel-id: "#log_a2b_alpha_deploy"
        payload: |
          {
            "text": "requested"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}

    - uses: slackapi/slack-github-action@v1.21.0
      if: ${{ github.event.workflow_run.conclusion == '' && github.workflow == 'production' }}
      with:
        channel-id: "#log_a2b_production_deploy"
        payload: |
          {
            "text": "requested"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}

  on-success:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.21.0
      if: ${{ github.event.workflow_run.conclusion == 'success' && github.workflow == 'alpha' }}
      with:
        channel-id: "#log_a2b_alpha_deploy"
        payload: |
          {
            "text": "success"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}

    - uses: slackapi/slack-github-action@v1.21.0
      if: ${{ github.event.workflow_run.conclusion == 'success' && github.workflow == 'production' }}
      with:
        channel-id: "#log_a2b_production_deploy"
        payload: |
          {
            "text": "success"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}

  on-failure:
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v1.21.0
      if: ${{ github.event.workflow_run.conclusion == 'failure' && github.workflow == 'alpha' }}
      with:
        channel-id: "#log_a2b_alpha_deploy"
        payload: |
          {
            "text": "failure"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}

    - uses: slackapi/slack-github-action@v1.21.0
      if: ${{ github.event.workflow_run.conclusion == 'failure' && github.workflow == 'production' }}
      with:
        channel-id: "#log_a2b_production_deploy"
        payload: |
          {
            "text": "failure"
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}
